### ISSUE TITLE
feat: option to host own tmdb-image proxy worker

### ISSUE THREAD

**Issue by GitGitro** [avalynndev/enjoytown#136]
Hi!

your proxy worker sometimes is rate limited and if you run `npm run build` it fails.

so i was considering to add an env variable to host the tmdb proxy .
let me know if it's doable since i haven't seen the source code for the proxy in your profile, if you open it i can consider implementing it myself!

**Comment by real-zephex** [comment]
https://github.com/real-zephex/Good-Proxy

**Comment by avalynndev** [comment]
@GitGitro kindly close this issue if your problem has been solved or ask a follow up so I can give a more valid response 0-0

**Comment by GitGitro** [comment]
yeah sorry, i managed to host my own proxy, i was testing to implement as enviroment variable but i'm stuck maybe you can help.

i've added the enviroment variable in env.mjs
```
import { createEnv } from "@t3-oss/env-nextjs";
import { vercel } from "@t3-oss/env-nextjs/presets";
import { z } from "zod";

export const env = createEnv({
  extends: [vercel()],
  shared: {
    GOOD_PROXY_URL: z.string().url(),
    DOWNLOAD_API_URL: z.string().url(),
    CONSUMET_API_URL: z.string().url(),
    CONSUMET_API_ANILIST_URL: z.string().url(),
    NODE_ENV: z
      .enum(["development", "production", "test"])
      .default("development"),
  },
  experimental__runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
```
i've modified the url.ts file accordingly with export const PROXY = `${env.GOOD_PROXY_URL}/api-json?url=`; 
and all the references in the files, but when i run it it crashes and says `Error: Invalid environment variables` .
i've googled everything but i can't find anything useful, any tips?

**Comment by real-zephex** [comment]
Uhmm, why are you making your life harder?
Why not just use `process.env.VARIABLE_NAME`?

Add NEXT_PUBLIC_ before the variable name (in .env) if using it in a client component.

**Comment by GitGitro** [comment]
oh you mean put `VARIABLE_NAME` inside the .env file and then call it with process.env?

**Comment by real-zephex** [comment]
Yep

Also you are using it wrong, the endpoint should be `/fetch?url=` (it automatically fetches the content type)

**Comment by GitGitro** [comment]
that i took from the code i didn't change it myself
https://github.com/avalynndev/enjoytown/blob/034437799d035e7f2eb8021a4fdd3825ad435e8c/config/url.ts#L14

should i change it as well while i'm at it?

**Comment by real-zephex** [comment]
Well, it's upto you 🤷‍♂️

**Comment by GitGitro** [comment]
ok i've changed them all and it's working.

the only thing that remains is modifying the next.config.js file because adding
```
{
        protocol: "https",
        hostname: `${process.env.GOOD_PROXY_URL}`,
},
```

it crashes, it needs to specify the protocol but this way ends up https://https://proxyurl...

any way to do this without hardcoding the remote in the next.config.js?

**Comment by GitGitro** [comment]
ok i found a solution, i'll open a pr that closes the issue soon
