### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by heyitsleo** [avalynndev/enjoytown#151]
6:13:17 PM:    Generating static pages (0/13) ...
6:13:19 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
6:13:19 PM: Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
6:13:19 PM: Error: Attempted to call viewport() from the server but viewport is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.
    at /opt/build/repo/.next/server/chunks/9432.js:1:32988
6:13:19 PM:     at /opt/build/repo/.next/server/chunks/3268.js:12:130313
6:13:19 PM:     at C (/opt/build/repo/.next/server/chunks/3268.js:12:130406)
6:13:19 PM:     at T (/opt/build/repo/.next/server/chunks/3268.js:13:1967)
6:13:19 PM:     at b (/opt/build/repo/.next/server/chunks/3268.js:12:125940)
6:13:19 PM: Export encountered an error on /_not-found/page: /_not-found, exiting the build.
6:13:19 PM:  ⨯ Static worker exited with code: 1 and signal: null
6:13:19 PM: ​
6:13:19 PM: "build.command" failed  

I pulled eveything from the repo, and my build keeps failing. Tried to delete cache and try again; didnt work.

**Comment by avalynndev** [comment]
Full Log will be appreciated

**Comment by heyitsleo** [comment]
6:06:32 PM: build-image version: ac04297350eb70143750579597f0ee10cba6ea6e (focal)
6:06:32 PM: buildbot version: ac04297350eb70143750579597f0ee10cba6ea6e
6:06:32 PM: Fetching cached dependencies
6:06:32 PM: Starting to download cache of 572.5MB
6:06:34 PM: Finished downloading cache in 1.991s
6:06:34 PM: Starting to extract cache
6:06:44 PM: Finished extracting cache in 9.94s
6:06:44 PM: Finished fetching cache in 12.032s
6:06:44 PM: Starting to prepare the repo for build
6:06:44 PM: Preparing Git Reference refs/heads/main
6:06:47 PM: Starting to install dependencies
6:06:47 PM: Started restoring cached mise cache
6:06:47 PM: Finished restoring cached mise cache
6:06:47 PM: Attempting Python version '3.8', read from environment
6:06:47 PM: downloading cpython-3.8.20+20241002-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz
6:06:48 PM: installing cpython-3.8.20+20241002-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz
6:06:48 PM: python --version
6:06:48 PM: Python 3.8.20
6:06:48 PM: mise python@3.8.20 ✓ installed
6:06:48 PM: Python version set to 3.8
6:06:48 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:06:48 PM: Attempting Ruby version 2.7.2, read from environment
6:06:50 PM: Using Ruby version 2.7.2
6:06:50 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:06:50 PM: Started restoring cached go cache
6:06:50 PM: Finished restoring cached go cache
6:06:50 PM: go version go1.19.13 linux/amd64
6:06:50 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:06:51 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:06:51 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:06:51 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:06:51 PM: Using PHP version 8.0
6:06:51 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:06:51 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:06:52 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:06:52 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:06:52 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:06:52 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:06:53 PM: Started restoring cached Node.js version
6:06:54 PM: Finished restoring cached Node.js version
6:06:54 PM: v20.18.0 is already installed.
6:06:55 PM: Now using node v20.18.0 (npm v10.8.2)
6:06:55 PM: Enabling Node.js Corepack
6:06:55 PM: Started restoring cached build plugins
6:06:55 PM: Finished restoring cached build plugins
6:06:55 PM: Started restoring cached corepack dependencies
6:06:55 PM: Finished restoring cached corepack dependencies
6:06:55 PM: No npm workspaces detected
6:06:55 PM: Started restoring cached node modules
6:06:55 PM: Finished restoring cached node modules
6:06:55 PM: Installing npm packages using npm version 10.8.2
6:07:09 PM: added 8 packages, removed 1 package, changed 17 packages, and audited 1191 packages in 14s
6:07:09 PM: 186 packages are looking for funding
6:07:09 PM:   run `npm fund` for details
6:07:09 PM: 2 moderate severity vulnerabilities
6:07:09 PM: Some issues need review, and may require choosing
6:07:09 PM: a different dependency.
6:07:09 PM: Run `npm audit` for details.
6:07:09 PM: npm packages installed
6:07:10 PM: Successfully installed dependencies
6:07:10 PM: Starting build script
6:07:10 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:07:10 PM: mise /opt/build/repo/.mise.toml tools: python@3.8.20
6:07:11 PM: Detected 1 framework(s)
6:07:11 PM: "next" at version "15.0.2"
6:07:11 PM: Section completed: initializing
6:07:13 PM: ​
6:07:13 PM: Netlify Build                                                 
6:07:13 PM: ────────────────────────────────────────────────────────────────
6:07:13 PM: ​
6:07:13 PM: ❯ Version
6:07:13 PM:   @netlify/build 29.55.5
6:07:13 PM: ​
6:07:13 PM: ❯ Flags
6:07:13 PM:   accountId: 63cae8d974077a026afc8087
6:07:13 PM:   baseRelDir: true
6:07:13 PM:   buildId: 6726a2554eb0e8000857ac07
6:07:13 PM:   deployId: 6726a2554eb0e8000857ac09
6:07:14 PM: ​
6:07:14 PM: ❯ Current directory
6:07:14 PM:   /opt/build/repo
6:07:14 PM: ​
6:07:14 PM: ❯ Config file
6:07:14 PM:   No config file was defined: using default values.
6:07:14 PM: ​
6:07:14 PM: ❯ Context
6:07:14 PM:   production
6:07:14 PM: ​
6:07:14 PM: ❯ Using Next.js Runtime - v5.8.1
6:07:16 PM: Next.js cache restored
6:07:16 PM: ​
6:07:16 PM: Build command from Netlify app                                
6:07:16 PM: ────────────────────────────────────────────────────────────────
6:07:16 PM: ​
6:07:16 PM: $ npm run build
6:07:17 PM: > enjoytown@2.1.0 build
6:07:17 PM: > next build
6:07:17 PM:    ▲ Next.js 15.0.2
6:07:17 PM:    Creating an optimized production build ...
6:07:48 PM: request to https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap failed, reason:
6:07:48 PM: Retrying 1/3...
6:08:02 PM:  ✓ Compiled successfully
6:08:02 PM:    Linting and checking validity of types ...
6:08:06 PM: ./app/drama/page.tsx
6:08:06 PM: 53:27  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
6:08:06 PM: ./app/manga/page.tsx
6:08:06 PM: 58:27  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
6:08:06 PM: ./components/carousal/card.tsx
6:08:06 PM: 15:9  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
6:08:06 PM: 39:9  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
6:08:06 PM: ./components/carousal/movie.tsx
6:08:06 PM: 15:1  Warning: Prevent client components from being async functions. See: https://nextjs.org/docs/messages/no-async-client-component  @next/next/no-async-client-component
6:08:06 PM: ./components/command-search.tsx
6:08:06 PM: 229:6  Warning: React Hook useEffect has a missing dependency: 'open'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
6:08:06 PM: ./components/common/card.tsx
6:08:06 PM: 23:13  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
6:08:06 PM: 55:13  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
6:08:06 PM: ./components/particles.tsx
6:08:06 PM: 91:6  Warning: React Hook useEffect has missing dependencies: 'animate' and 'initCanvas'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
6:08:06 PM: 95:6  Warning: React Hook useEffect has a missing dependency: 'onMouseMove'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
6:08:06 PM: 99:6  Warning: React Hook useEffect has a missing dependency: 'initCanvas'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
6:08:06 PM: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
6:08:15 PM:    Collecting page data ...
6:08:23 PM:    Generating static pages (0/13) ...
6:08:25 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
6:08:25 PM: Error occurred prerendering page "/list/anime". Read more: https://nextjs.org/docs/messages/prerender-error
6:08:25 PM: Error: Attempted to call viewport() from the server but viewport is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.
    at /opt/build/repo/.next/server/chunks/9432.js:1:32987
6:08:25 PM:     at /opt/build/repo/.next/server/chunks/3268.js:12:130313
6:08:25 PM:     at C (/opt/build/repo/.next/server/chunks/3268.js:12:130406)
6:08:25 PM:     at T (/opt/build/repo/.next/server/chunks/3268.js:13:1967)
6:08:25 PM:     at b (/opt/build/repo/.next/server/chunks/3268.js:12:125940)
6:08:25 PM: Export encountered an error on /list/anime/page: /list/anime, exiting the build.
6:08:25 PM:  ⨯ Static worker exited with code: 1 and signal: null
6:08:25 PM: ​
6:08:25 PM: "build.command" failed                                        
6:08:25 PM: ────────────────────────────────────────────────────────────────
6:08:25 PM: ​
6:08:25 PM:   Error message
6:08:25 PM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
6:08:25 PM: ​
6:08:25 PM:   Error location
6:08:25 PM:   In Build command from Netlify app:
6:08:25 PM:   npm run build
6:08:25 PM: ​
6:08:25 PM:   Resolved config
6:08:25 PM:   build:
6:08:25 PM:     command: npm run build
6:08:25 PM:     commandOrigin: ui
6:08:25 PM:     environment:
6:08:25 PM:       - CONSUMET_API_ANILIST_URL
6:08:25 PM:       - CONSUMET_API_URL
6:08:25 PM:       - DOWNLOAD_API_URL
6:08:25 PM:     publish: /opt/build/repo/.next
6:08:25 PM:     publishOrigin: ui
6:08:25 PM:   plugins:
6:08:25 PM:     - inputs: {}
6:08:25 PM:       origin: ui
6:08:25 PM:       package: '@netlify/plugin-nextjs'
6:08:25 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
6:08:25 PM: Failing build: Failed to build site
6:08:26 PM: Finished processing build request in 1m54.005s

**Comment by heyitsleo** [comment]
It's not just this page, it's also happening elsewhere.

**Comment by avalynndev** [comment]
i have no idea why this is occurring.. i don't face the issue.. could u give the steps to reproduce it?

**Comment by heyitsleo** [comment]
i just pulled and fixed conflicts. perhaps i could give you access to my repository and you could try with that?

**Comment by avalynndev** [comment]
That would be nice

**Comment by heyitsleo** [comment]
I just re-downloaded my code and returned my tweaks and it works fine. It was strange how it didn't build without me just completely moving and downloading the latest version.
