### ISSUE TITLE
bug: cmd search

### ISSUE THREAD

**Issue by heyitsleo** [avalynndev/enjoytown#158]
i sometimes recieve no results when searching for things, i've tried between mobile and other things. it could be the localstorage part saving every keyword you search (h, he, hel, hell, hello) when i think it should use the id the user clicks on and save it like that instead the other ways. thus it makes it easier to return to previous shows you've searched, and better stability.

**Comment by avalynndev** [comment]
thats a good point.. will try solving it

**Comment by heyitsleo** [comment]
fixed myself, i just ended up making a search page 🤷
