### ISSUE TITLE
[feat]: Add a license to project

### ISSUE THREAD

**Issue by thewbuk** [avalynndev/enjoytown#159]
### What went wrong?

Add license to project

### How'd you stumble upon it?

Add license to project

### What you hoped for vs. What actually happened

Add license to project

### Which browsers were a bummer?

Microsoft Edge

### Got logs?

```shell
Add license to project
```

### Code of Conduct Agreement

- [X] I agree to follow this project's Code of Conduct.

**Comment by avalynndev** [comment]
idk wt license to add 0-0

**Comment by heyitsleo** [comment]
https://choosealicense.com/appendix/

**Comment by avalynndev** [comment]
will read

**Comment by avalynndev** [comment]
Solved
