### ISSUE TITLE
[Bug]: Serach bar

### ISSUE THREAD

**Issue by ShivamPansuriya** [avalynndev/enjoytown#22]
### What went wrong?

when ever I am hitting search it is giving me blank page I that that after last commit this problem is arising 

### How'd you stumble upon it?

doing filter search

### What you hoped for vs. What actually happened

search bar 

### Which browsers were a bummer?

Chrome

### Code of Conduct Agreement

- [X] I agree to follow this project's Code of Conduct.

**Comment by lennoncoder** [comment]
@ShivamPansuriya would you please state where exactly are you getting the problem?

**Comment by avalynndev** [comment]
Fixed, thx to @lennoncoder
