### ISSUE TITLE
feat: season and episode dropdown

### ISSUE THREAD

**Issue by flawsom** [avalynndev/enjoytown#23]
When you enter the "tv shows" catalogue..
there's no option to move to the next episode ,
there's no selection dropdown for it 
same goes for the season
Hope you can fix it sooner

![Screenshot (26)](https://github.com/avalynndev/enjoytown/assets/64182228/e339dfed-8df3-4325-8d8c-030b8b56b2e3)

**Comment by avalynndev** [comment]
@flawsom, Firstly thank you for creating this issue, however this issue was already brought to my notice by one of my friends, i added it to my list of tasks to make this website better you can check the task list here #17

**Comment by flawsom** [comment]
ah alright, also i noticed vid pro has a better playback rate for most of the shows, it would be great to have that as the default instead.
