### ISSUE TITLE
(feat): download option

### ISSUE THREAD

**Issue by Aruraka** [avalynndev/enjoytown#3]

**Comment by avalynndev** [comment]
Hii there just a request can u add download option too in different qualities from  240 p to 480p so that we can download series in it? otherwise the app is nice and nice ui too

**Comment by avalynndev** [comment]
@Aruraka Unfortunately i cant add it for k-drama or movies. i can only add it for anime, and manga :(, if that's what you want sure, il add it

**Comment by avalynndev** [comment]
This feature would be implemented in around 2 weeks bcuz of the insane amount of feat requests i'm getting for this website

**Comment by Aruraka** [comment]
> This feature would be implemented in around 2 weeks bcuz of the insane amount of feat requests i'm getting for this website

Thanks so much btw when I open a drama it's appearing blank tho
![Screenshot_20240521_083733_Chrome](https://github.com/avalynndev/enjoytown/assets/159518209/834e835b-c531-41fe-be81-4f8d7f16e788)

**Comment by avalynndev** [comment]
it works now

**Comment by Aruraka** [comment]
> it works now

Yeah it's working now thanks 😊

**Comment by avalynndev** [comment]
added download button to kdrama section along with tv :)
