### ISSUE TITLE
Search Index is not working

### ISSUE THREAD

**Issue by flawsom** [avalynndev/enjoytown#31]
Search function for searching movies isn't working 

![Screenshot (28)](https://github.com/avalynndev/enjoytown/assets/64182228/1c32f133-46f3-4dd4-b2b7-b80c4e33d98f)

**Comment by lennoncoder** [comment]
![image](https://github.com/avalynndev/enjoytown/assets/87892177/2c7e9b70-5ee6-4566-9544-073e60b1a154)

**Comment by flawsom** [comment]
Not for me tho 
It still doesn't work

**Comment by lennoncoder** [comment]
console.log errors?

**Comment by RounakDadsena** [comment]
check now

**Comment by flawsom** [comment]
Nope it still doesn't work

![Screenshot (29)](https://github.com/avalynndev/enjoytown/assets/64182228/101b6b8d-aaaa-4c36-84b9-e1a96c775ff7)

**Comment by avalynndev** [comment]
What the, it works fine for all the others

**Comment by RounakDadsena** [comment]
![image](https://github.com/avalynndev/enjoytown/assets/87689078/d921073f-4253-4425-850d-9bae6caeed5d)
see it is working for me

**Comment by flawsom** [comment]
still not for me tho 
![Screenshot (30)](https://github.com/avalynndev/enjoytown/assets/64182228/b06dab8b-278a-4d91-9610-5d33cd3c30bd)

**Comment by RounakDadsena** [comment]
Try using different Browser

**Comment by flawsom** [comment]
nah that doesn't work aswell 
![Screenshot (31)](https://github.com/avalynndev/enjoytown/assets/64182228/31d6209d-36d3-4799-bb98-a681d1a9f484)

**Comment by avalynndev** [comment]
from how long are you facing this problem? state the commit id plz

**Comment by flawsom** [comment]
> from how long are you facing this problem? state the commit id plz

I hadn't used the search feature earlier, until the day u announced the addition of hindi movies
so idk if it was from the begining or arised to to a certain commit

**Comment by avalynndev** [comment]
frnd me on discord `avalynndev`, or if we r already frnds send hi

**Comment by avalynndev** [comment]
@flawsom is it fixed?

**Comment by flawsom** [comment]
Nope, still haven't

**Comment by avalynndev** [comment]
@flawsom there is a new update called Enjoytown v2, your problem will probably be solved then. so I'm closing this issue. if you still face the problem even after v2 update kindly reopen it
