### ISSUE TITLE
[bug]: add anilist search feat

### ISSUE THREAD

**Issue by aditya-kumarr** [avalynndev/enjoytown#43]
### What went wrong?

Facing application error on anime page

### How'd you stumble upon it?

I searched one piece (dub)
clicked on it
and the page threw a client side error

### What you hoped for vs. What actually happened

the page for anime should've opened but it went all white with a client side error

### Anything else we should know?

This happened in arc browser, there was no such error before this day, likely caused by latest commit

### Which browsers were a bummer?

Chrome

### Got logs?

```shell
# There wasn't much but this all that was there

7023-3851d4a3172f44ef.js:1 
Error: Connection closed.
    at t (7023-3851d4a3172f44ef.js:2:17782)
window.console.error	@	7023-3851d4a3172f44ef.js:1
l_	@	fd9d1056-158ac2c9d594a992.js:1
n.callback	@	fd9d1056-158ac2c9d594a992.js:1
nB	@	fd9d1056-158ac2c9d594a992.js:1
nV	@	fd9d1056-158ac2c9d594a992.js:1
aq	@	fd9d1056-158ac2c9d594a992.js:1
aY	@	fd9d1056-158ac2c9d594a992.js:1
a9	@	fd9d1056-158ac2c9d594a992.js:1
aY	@	fd9d1056-158ac2c9d594a992.js:1
a9	@	fd9d1056-158ac2c9d594a992.js:1
aY	@	fd9d1056-158ac2c9d594a992.js:1
a9	@	fd9d1056-158ac2c9d594a992.js:1
aY	@	fd9d1056-158ac2c9d594a992.js:1
a9	@	fd9d1056-158ac2c9d594a992.js:1
aY	@	fd9d1056-158ac2c9d594a992.js:1
a9	@	fd9d1056-158ac2c9d594a992.js:1
aY	@	fd9d1056-158ac2c9d594a992.js:1
a9	@	fd9d1056-158ac2c9d594a992.js:1
aY	@	fd9d1056-158ac2c9d594a992.js:1
a9	@	fd9d1056-158ac2c9d594a992.js:1
aY	@	fd9d1056-158ac2c9d594a992.js:1
a9	@	fd9d1056-158ac2c9d594a992.js:1
aY	@	fd9d1056-158ac2c9d594a992.js:1
(anonymous)	@	fd9d1056-158ac2c9d594a992.js:1
is	@	fd9d1056-158ac2c9d594a992.js:1
o1	@	fd9d1056-158ac2c9d594a992.js:1
oZ	@	fd9d1056-158ac2c9d594a992.js:1
T	@	7023-3851d4a3172f44ef.js:1
```

### Code of Conduct Agreement

- [x] I agree to follow this project's Code of Conduct.

**Comment by avalynndev** [comment]
@aditya-kumarr firstly thank you for bringing this to my notice, 2ndly i forgot about the search function.. i am gonna add it soon..

**Comment by avalynndev** [comment]
for now please try to adjust w one piece on the home page itself.. 💯

**Comment by aditya-kumarr** [comment]
I think that was because of  search returns kebab casing names as Ids where as the info page takes it as int
Either way thanks man, would love to contribute here

**Comment by avalynndev** [comment]
lemme explain to you boi, I used gogoanime-api to fetch details until now.. however i realized anilist is better. so i switched. but when i switched i forgot to change the search code to make it work for anilist.. thats why both of them dont go hand in hand :)

**Comment by avalynndev** [comment]
Anyways @aditya-kumarr, the problem is solved.. :)
