### ISSUE TITLE
feat. add option to download anime

### ISSUE THREAD

**Issue by flawsom** [avalynndev/enjoytown#64]
use vid streaming or gogo hd.net apis to fetch these links

**Comment by avalynndev** [comment]
can you gibe some sample code cuz I have no idea how to make it work lmao

**Comment by flawsom** [comment]
![image](https://github.com/user-attachments/assets/4b6532a7-94aa-4f49-aaad-78475d768f86)

So here's a sample ( Source : Miruro )


here's the guide:
### Initialize State
First, create a state/constant to hold the download link.

```ts
const [downloadLink, setDownloadLink] = useState('');
```
### Fetch Download Link
Fetch the episode data and extract the download link.

```ts
useEffect(() => {
  const fetchEpisodeData = async (episodeId) => {
    try {
      const response = await fetch(`https://miruro-api.vercel.app/meta/anilist/watch/${episodeId}`);
      const data = await response.json();
      setDownloadLink(data.download); // Grab that download link
    } catch (error) {
      console.error('Failed to fetch episode data', error);
    }
  };

  fetchEpisodeData('spy-x-family-episode-1'); // Replace with your dynamic episode ID
}, []);
```
### Create Download Button
Anddd then just create a button that uses the download link to let users download the episode.

```tsx
const handleDownload = () => {
  if (downloadLink) {
    window.open(downloadLink, '_blank');
  }
};

return (
  <button onClick={handleDownload} disabled={!downloadLink}>
    Download Episode
  </button>
);
```
So yeah It's basically just getting the download URL from the API's response and setting it into a button.
### Tip
The download links from gogohd.net have expiry dates in the URL as parameters:
https://gogohd.net/download?id=MTg0MTQx&token=hrSJyxdvpab7Jupw-b4Hgw&expires=1722015011

To get rid of the expiry date so you can store the link forever, just remove the `expires` and `token` parameters:
https://gogohd.net/download?id=MTg0MTQx

**Comment by flawsom** [comment]
also add eenv examples for movies, kdrama, series and manga sites

**Comment by avalynndev** [comment]
why add env example for all of them? itz included in the env example in the root

> also add eenv examples for movies, kdrama, series and manga sites

**Comment by avalynndev** [comment]
https://gogohd.net/download?id=MTg0MTQx
doesn't work for me, cuz the url is blocked in my country

**Comment by flawsom** [comment]
> why add env example for all of them? itz included in the env example in the root
> 
> > also add eenv examples for movies, kdrama, series and manga sites

but won't that exaust ur own instance or u meant something else ?

**Comment by flawsom** [comment]
> https://gogohd.net/download?id=MTg0MTQx doesn't work for me, cuz the url is blocked in my country

Alright try with 
https://s3taku.com/download?id=MTg0MTQx

**Comment by avalynndev** [comment]
it works but how do i fetch this?

> > https://gogohd.net/download?id=MTg0MTQx doesn't work for me, cuz the url is blocked in my country
> 
> Alright try with https://s3taku.com/download?id=MTg0MTQx

**Comment by avalynndev** [comment]
> > why add env example for all of them? itz included in the env example in the root
> > > also add eenv examples for movies, kdrama, series and manga sites
> 
> but won't that exaust ur own instance or u meant something else ? I thought creating ur own api instances would be better if u could specify which one's

ngl i didnt understand whatt u just said, can you explain more clearly?

**Comment by flawsom** [comment]
> it works but how do i fetch this?
> 
> > > https://gogohd.net/download?id=MTg0MTQx doesn't work for me, cuz the url is blocked in my country
> > 
> > 
> > Alright try with https://s3taku.com/download?id=MTg0MTQx

Just use https://s3taku.com/download?id= 
as string and fetch the anilist I'd from the consumet api using 
https://your-consumet-api/meta/anilist/watch/${episodeId}
And just add it to the back of the string

**Comment by flawsom** [comment]
> > > why add env example for all of them? itz included in the env example in the root
> > > > also add eenv examples for movies, kdrama, series and manga sites
> > 
> > 
> > but won't that exaust ur own instance or u meant something else ? I thought creating ur own api instances would be better if u could specify which one's
> 
> ngl i didnt understand whatt u just said, can you explain more clearly?

My discord is @vibes.him we r friends there, 
Could u just specify the envs for the movies and all there ( and which hosting service - vercel, netlify, fly or do or workers ur using )

**Comment by avalynndev** [comment]
> > it works but how do i fetch this?
> > > > https://gogohd.net/download?id=MTg0MTQx doesn't work for me, cuz the url is blocked in my country
> > > 
> > > 
> > > Alright try with https://s3taku.com/download?id=MTg0MTQx
> 
> Just use https://s3taku.com/download?id= as string and fetch the anilist I'd from the consumet api using [https://your-consumet-api/meta/anilist/watch/${episodeId}](https://your-consumet-api/meta/anilist/watch/$%7BepisodeId%7D) And just add it to the back of the string

yep that works

**Comment by flawsom** [comment]
heyy any updates ?

**Comment by avalynndev** [comment]
I forgot about this

**Comment by flawsom** [comment]
:/

**Comment by avalynndev** [comment]
;-;

**Comment by avalynndev** [comment]
[0a11ac6](https://github.com/avalynndev/enjoytown/commit/0a11ac67bde7f4bf78b4ef172b23db96ced1d1aa)
