### ISSUE TITLE
Error when accessing anime section

### ISSUE THREAD

**Issue by dillfrescott** [avalynndev/enjoytown#9]
![Screenshot 2024-05-25 184557](https://github.com/avalynndev/enjoytown/assets/56714680/ef35bff3-6674-45b9-8360-7c34e0f5638f)

It seems to be happening on the official instance too. :(

**Comment by skgupta507** [comment]
hey @avalynndev even i faced the same issue on the main site
the anime section is not accessable. it shows a blank screen.
pls look in to it

**Comment by avalynndev** [comment]
the error is going to be fixed in a min.

**Comment by avalynndev** [comment]
itz fixed now

**Comment by avalynndev** [comment]
Just update update ur repository and the env template is:
```env
DOWNLOAD_API_URL=https://v1.api.ani.rohi.dev/api/dramacool
```

**Comment by dillfrescott** [comment]
Cool! Thanks!

**Comment by avalynndev** [comment]
no problem
